"""
b4_op_build_templates.py

Builds DOCX templates from MD source files for klasa 2 (parametryzowana) types
in podprojekt-b/B4-operacyjne. Each template is generated by stripping YAML
frontmatter from the MD body and converting the body via Pandoc.

The templates retain {{PLACEHOLDER}} markers that the generator scripts
substitute with values from CSV data per cycle.

Usage:
    python scripts/b4_op_build_templates.py
    python scripts/b4_op_build_templates.py --verify-only

Output:
    <B4-operacyjne>/<grupa>/<typ>/templates/template_<lang>.docx (10 files)
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
B4_ROOT = REPO_ROOT / "podprojekt-b" / "B4-operacyjne"


@dataclass(frozen=True)
class TemplateSpec:
    typ_path: str
    languages: tuple[str, ...]
    expected_id: str

    @property
    def slug(self) -> str:
        return self.typ_path.split("/")[-1]


KLASA_2_TYPES: tuple[TemplateSpec, ...] = (
    TemplateSpec("O1-wejscie/04-karta-uczestnika", ("pl", "en", "es", "uk"), "KU-1.0/2026"),
    TemplateSpec("O1-wejscie/05-lista-kwalifikowanych", ("pl",), "LK-1.0/2026"),
    TemplateSpec("O2-realizacja/01-harmonogram-szczegolowy", ("pl",), "HSZ-1.0/2026"),
    TemplateSpec("O2-realizacja/04-zbiorcza-karta-obecnosci", ("pl", "en", "es", "uk"), "ZKO-1.0/2026"),
    TemplateSpec("O3-ocena/07-karta-odpowiedzi", ("pl", "en", "es", "uk"), "KO-1.0/2026"),
)


def strip_yaml_frontmatter(md_text: str) -> str:
    """Remove YAML frontmatter block delimited by --- ... --- at the document start."""
    if not md_text.startswith("---\n"):
        return md_text
    end = md_text.find("\n---\n", 4)
    if end == -1:
        return md_text
    return md_text[end + 5 :]


def extract_placeholders(text: str) -> set[str]:
    return set(re.findall(r"\{\{[A-Z_]+\}\}", text))


def convert_md_to_docx(md_body: str, output_path: Path) -> None:
    """Convert Markdown body (no YAML) to DOCX via Pandoc."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [
            "pandoc",
            "--from=markdown+yaml_metadata_block-raw_html",
            "--to=docx",
            "-o",
            str(output_path),
        ],
        input=md_body.encode("utf-8"),
        capture_output=True,
        timeout=60,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Pandoc failed for {output_path}: {result.stderr.decode('utf-8', errors='replace')}"
        )


def verify_docx_placeholders(docx_path: Path, expected: set[str]) -> tuple[bool, set[str]]:
    """Open DOCX and verify all expected placeholders are present in body or tables."""
    from docx import Document  # type: ignore[import-untyped]

    doc = Document(str(docx_path))
    text_blob: list[str] = []
    for paragraph in doc.paragraphs:
        text_blob.append(paragraph.text)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    text_blob.append(paragraph.text)
    body_text = "\n".join(text_blob)
    found = extract_placeholders(body_text)
    missing = expected - found
    return (not missing, missing)


def build_one(spec: TemplateSpec, lang: str, verify_only: bool) -> tuple[Path, dict]:
    md_path = B4_ROOT / spec.typ_path / f"{lang}.md"
    docx_path = B4_ROOT / spec.typ_path / "templates" / f"template_{lang}.docx"

    md_text = md_path.read_text(encoding="utf-8")
    expected_placeholders = extract_placeholders(md_text)
    body = strip_yaml_frontmatter(md_text)

    if not verify_only:
        convert_md_to_docx(body, docx_path)

    if not docx_path.exists():
        return docx_path, {"error": "DOCX not produced"}

    placeholder_ok, missing = verify_docx_placeholders(docx_path, expected_placeholders)
    size = docx_path.stat().st_size
    return docx_path, {
        "size": size,
        "expected_placeholders": len(expected_placeholders),
        "placeholder_ok": placeholder_ok,
        "missing": missing,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify-only", action="store_true", help="Skip conversion, only verify existing DOCX")
    args = parser.parse_args(argv)

    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]

    print(f"{'typ':<45} {'lang':<4} {'size':>6} {'placeholders':>12} status")
    print("-" * 80)

    issues: list[str] = []
    total_size = 0
    files_built = 0

    for spec in KLASA_2_TYPES:
        for lang in spec.languages:
            try:
                docx_path, info = build_one(spec, lang, args.verify_only)
            except Exception as exc:
                issues.append(f"{spec.typ_path}/{lang}: {exc}")
                print(f"{spec.slug:<45} {lang:<4} ERROR: {exc}")
                continue
            status = "OK" if info.get("placeholder_ok") else f"MISSING {info.get('missing', set())}"
            print(
                f"{spec.slug:<45} {lang:<4} {info.get('size', 0):>6} "
                f"{info.get('expected_placeholders', 0):>12} {status}"
            )
            if not info.get("placeholder_ok"):
                issues.append(f"{spec.typ_path}/{lang}: missing {info.get('missing')}")
            total_size += info.get("size", 0)
            files_built += 1

    print("-" * 80)
    print(f"TOTAL: {files_built} DOCX templates, {total_size} bytes ({total_size / 1024:.1f} KB)")
    if issues:
        print(f"ISSUES: {len(issues)}")
        for issue in issues:
            print(f"  {issue}")
        return 1
    print("NO ISSUES")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
